"""Add UniqueConstraint for daily_price

Revision ID: 25fce2216df6
Revises: beba1700a267
Create Date: 2021-03-27 20:02:10.699724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fce2216df6'
down_revision = 'beba1700a267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_symbol_price_uc', 'daily_price', ['symbol_id', 'price_date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_symbol_price_uc', 'daily_price', type_='unique')
    # ### end Alembic commands ###
