"""Add stockscreener tables

Revision ID: beba1700a267
Revises: d4867f3a4c0a
Create Date: 2021-03-22 20:21:23.316882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beba1700a267'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbrev', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('timezone_offset', sa.Time(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbrev')
    )
    op.create_index(op.f('ix_exchange_id'), 'exchange', ['id'], unique=False)
    op.create_index(op.f('ix_exchange_name'), 'exchange', ['name'], unique=False)
    op.create_table('stock_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_stock_category_id'), 'stock_category', ['id'], unique=False)
    op.create_table('stock_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbrev', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbrev')
    )
    op.create_index(op.f('ix_stock_index_id'), 'stock_index', ['id'], unique=False)
    op.create_table('symbol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('stock_index_id', sa.Integer(), nullable=True),
    sa.Column('stock_category_id', sa.Integer(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], ),
    sa.ForeignKeyConstraint(['stock_category_id'], ['stock_category.id'], ),
    sa.ForeignKeyConstraint(['stock_index_id'], ['stock_index.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbol_id'), 'symbol', ['id'], unique=False)
    op.create_index(op.f('ix_symbol_ticker'), 'symbol', ['ticker'], unique=True)
    op.create_table('daily_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=True),
    sa.Column('price_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('high_price', sa.DECIMAL(), nullable=False),
    sa.Column('open_price', sa.DECIMAL(), nullable=False),
    sa.Column('low_price', sa.DECIMAL(), nullable=False),
    sa.Column('close_price', sa.DECIMAL(), nullable=False),
    sa.Column('adj_close_price', sa.DECIMAL(), nullable=False),
    sa.Column('volume', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_price_id'), 'daily_price', ['id'], unique=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_daily_price_id'), table_name='daily_price')
    op.drop_table('daily_price')
    op.drop_index(op.f('ix_symbol_ticker'), table_name='symbol')
    op.drop_index(op.f('ix_symbol_id'), table_name='symbol')
    op.drop_table('symbol')
    op.drop_index(op.f('ix_stock_index_id'), table_name='stock_index')
    op.drop_table('stock_index')
    op.drop_index(op.f('ix_stock_category_id'), table_name='stock_category')
    op.drop_table('stock_category')
    op.drop_index(op.f('ix_exchange_name'), table_name='exchange')
    op.drop_index(op.f('ix_exchange_id'), table_name='exchange')
    op.drop_table('exchange')
    # ### end Alembic commands ###
